Repository exercism/batch, pull requests merged in 2024-09, with the labels that each got.

#45 LAUNCH 🚀
  config.json
Labels: new track

#46 ci(dependabot): change to monthly interval
  .github/dependabot.yml
Labels: x:size/tiny

#57 Update tests.toml files
  exercises/practice/acronym/.meta/tests.toml
  exercises/practice/armstrong-numbers/.meta/tests.toml
  exercises/practice/clock/.meta/tests.toml
  exercises/practice/darts/.meta/tests.toml
  exercises/practice/difference-of-squares/.meta/tests.toml
  exercises/practice/food-chain/.meta/tests.toml
  exercises/practice/grains/.meta/tests.toml
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/nth-prime/.meta/tests.toml
  exercises/practice/nucleotide-count/.meta/tests.toml
  exercises/practice/proverb/.meta/tests.toml
  exercises/practice/raindrops/.meta/tests.toml
  exercises/practice/resistor-color/.meta/tests.toml
  exercises/practice/reverse-string/.meta/tests.toml
  exercises/practice/scrabble-score/.meta/tests.toml
  exercises/practice/series/.meta/tests.toml
  exercises/practice/sieve/.meta/tests.toml
  exercises/practice/square-root/.meta/tests.toml
  exercises/practice/two-fer/.meta/tests.toml
Labels: x:size/large, x:rep/large

#68 `hamming` - two confusing test remove
  exercises/practice/hamming/HammingTest.bat
Labels: fix
